path: /nfs-data2/tungtx2/class_surveillance/train_detector/data/
train:
  - laptop/laptop_dataset_processed/with_person/train
  - laptop/laptop_dataset_processed/without_person/train
  - laptop/coco/train
  - crowdhuman-vbox-no_laptop-10k/train
val:
  - laptop/laptop_dataset_processed/with_person/val
  - laptop/laptop_dataset_processed/without_person/val
  - laptop/coco/val
  - crowdhuman-vbox-no_laptop-10k/val

names:
  0: person
  1: head
  2: laptop